### ISSUE TITLE
Build Acceptance API

### ISSUE THREAD

**Issue by wresuolc** [mozilla/watchdog-proxy#1]
Whenever a consumer is provided a new image by a user, it POSTs that image to Watchdog, along with callback URIs for positive and negative cases, an optional free-text notes field, and an optional email address to which reports of positives should be sent.  An example request:

> POST /submit HTTP/1.1
> Host: watchdog.mozilla.org
> Accept: application/json
> Authorization = Watchdog AKIAIOSFODNN7EXAMPLE:4643978965ffcec6e6d73b36a39ae43ceb15f7ef8131b8307862ebc560e7f988
> Content-Type: multipart/form-data; boundary=---------------------------012345677890
>  
> -----------------------------012345677890
> Content-Disposition: form-data; name="negative_uri"
>  
> https://screenshots.firefox.com/watchdog/verify/negative?file_id=012345677890&nonce=abcdefghij
> -----------------------------012345677890
> Content-Disposition: form-data; name="positive_uri"
>  
> https://screenshots.firefox.com/watchdog/verify/positive?file_id=012345677890&nonce=abcdefghij
> -----------------------------012345677890
> Content-Disposition: form-data; name="positive_email[]"
>  
> screenshots@m.c
> -----------------------------012345677890
> Content-Disposition: form-data; name=“notes”
>  
> Uploaded on 2018-01-01 at 12:00:00 PM by user@example.com from 123.45.67.890
> -----------------------------012345677890
> Content-Disposition: form-data; name="image"; filename="image_name.png"
> Content-Type: image/png
>  
> Content of image_name.png
> -----------------------------012345677890--

Watchdog will return a response confirming receipt of the submission, including a Watchdog request identifier (a UUID version 4) that the consumer can use to associate with future requests from Watchdog:

> HTTP/1.1 201 Created
> Host: screenshots.firefox.com
> Content-Type: application/json
>  
> {
>     "negative_uri": "https://screenshots.firefox.com/watchdog/verify/negative?file_id=012345677890&nonce=abcdefghij",
>     "positive_uri": "https://screenshots.firefox.com/watchdog/verify/positive?file_id=012345677890&nonce=abcdefghij",
>     "positive_email": "screenshots@m.c",
>     "id": "5a416211-f09e-4183-a8e1-4137acfa10f2"
> }

- The Acceptance header here will be detailed in a separate issue.
- This issue includes checking user input to make user it's reasonably well-formed
- Valid user input is stored in the queue (SQS)

**Comment by pdehaan** [comment]
Would a positive match be automatically removed? Or does it need to go through some sort of manual verification?

**Comment by chenba** [comment]
On the consumer side, and I can only speak for Screenshots, the image will no longer be accessible as soon as Watchdog reports a positive match.  The image and related data will be retained for further review.

**Comment by lmorchard** [comment]
FWIW, got a start on this as a Lambda function triggered from an API Gateway endpoint

https://github.com/mozilla/watchdog-proxy/blob/master/functions/accept.js
