### ISSUE TITLE
Continually deploy a dev stack from master

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#11]
Might be nice to set up some credentials and a named stage to deploy to AWS on every commit to master.

**Comment by lmorchard** [comment]
Would also be nice to have a more sensible & stable URL than for example:

https://5cjbgnv0ek.execute-api.us-east-1.amazonaws.com/lmorchard/accept

**Comment by lmorchard** [comment]
Not sure if this ends up being useful for production, but we could set up a stable domain name using the `serverless-domain-manager` plugin:

https://serverless.com/blog/serverless-api-gateway-domain/

**Comment by chenba** [comment]
Definitely would be nice for consumers to have a running service to test against.

I think we need Ops for this?  @oremj or @autrilla is this something you can help with? What do you need from us if so?

**Comment by chenba** [comment]
I was think of setting it up, not the act of deploying.  But really, I don't know who has access to set up an official-ish (*.mozaws.net?) domain for this purpose.

**Comment by lmorchard** [comment]
We can pretty much self-service any domains under `*.dev.mozaws.net`. I'm playing around with something like `watchdog-proxy-{stage}.dev.mozaws.net` as a pattern

**Comment by lmorchard** [comment]
This should be working now
