### ISSUE TITLE
Revise systems diagram after pollQueue removal

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#119]
In PR #117, the `pollQueue` function is replaced with new events emitted by a built-in SQS poller provided by Amazon. So, some changes are in order:

* Remove CloudWatch events - the alarm every 60s is gone
* Remove Queue Processor function - this is now built into SQS
* Event Processor now talks to DynamoDB to track rate limiting
* SQS now invokes Event Processor directly with events from the built-in poller

**Comment by lmorchard** [comment]
Oh yeah, and considering PR #130 will start sending email:

* Add an SES (simple email service) block with an arrow from the Event Processor - i.e. the Event Processor uses SES to send email notifications on positive matches

**Comment by clouserw** [comment]
How's this?

![image](https://user-images.githubusercontent.com/80098/43793705-2eb8c55c-9a31-11e8-83d4-28873a34783e.png)

**Comment by lmorchard** [comment]
One tweak: The Accept API function does also talk to DynamoDB for Hawk credentials. I think we might have left that out of the original diagram. So, maybe move the DBD block up & to the left and add another arrow to Accept API.

**Comment by clouserw** [comment]
![image](https://user-images.githubusercontent.com/80098/43794604-ade8c8e8-9a33-11e8-8d81-008c84f2ce60.png)

**Comment by lmorchard** [comment]
Yup, looks good to me! :shipit:
