### ISSUE TITLE
Throw Error When PhotoDNA Response is Not 3000

### ISSUE THREAD

**Issue by chenba** [mozilla/watchdog-proxy#173]
PhotoDNA returns a HTTP 200 even when there's an error processing a request.  It returns its own status code in the response:

- 3000: OK
- 3002: Invalid or missing request parameter(s)
- 3004: Unknown scenario or unhandled error occurred while processing request
- 3206: The given file could not be verified as an image
- 3208: Image size in pixels is not within allowed range (minimum size is 160x160 pixels; maximum size is 4MB)

(Copied from [teh docs](https://developer.microsoftmoderator.com/docs/services/57c7426e2703740ec4c9f4c3/operations/57c7426f27037407c8cc69e6?ref=mktg))

We should throw an error when the PhotoDNA status code is not 3000.

**Comment by chenba** [comment]
I agree that the consumers should be notified of the PhotoDNA errors.  (It's especially relevant if it's the 4MB limit.)  The most important thing is that the consumers do not receive a false negative, which is the current behavior.

**Comment by lmorchard** [comment]
Hmm, still not sure what to do here... maybe add an `isError: true` to the callback request if the response !== 3000?
