### ISSUE TITLE
Add CloudWatch alarm to periodically execute metrics function

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#187]
We merged PR #177, which adds a new periodic metrics function. Added [a once-per-minute CloudWatch alarm in serverless config](https://github.com/mozilla/watchdog-proxy/pull/177/files#diff-63cc6a6bda3bacebd211a20b638c91f1R150) to run the function.

This alarm needs to be added to the mozilla/cloudops-deployment config.

**Comment by oremj** [comment]
This has been deployed.
