### ISSUE TITLE
Send HSTS Header in Responses

### ISSUE THREAD

**Issue by chenba** [mozilla/watchdog-proxy#191]
It's on **The Security Checklist** (#34)

**Comment by chenba** [comment]
`strict-transport-security: max-age=31536000` according to the checklist

**Comment by lmorchard** [comment]
Hmm, do we actually need this? HSTS sounds like a thing aimed at telling browsers to use HTTPS over HTTP - but this is not a site for browser consumption, it's a server-to-server proxy service.

**Comment by chenba** [comment]
That was my thought as well.  There's also the question of how the HTTP client of the consumer will handle that header.  Assuming the client doesn't use the preload list or the domain is not on the preload list, but do handle HSTS, then when there's a misconfiguration on the consumer side to use HTTP, only the first request will be over HTTP.

A lot of ifs, but since we are sending over users' images, I think it's worthwhile to add it.

**Comment by clouserw** [comment]
@moz-jvehent -- would you confirm if this is required?

**Comment by lmorchard** [comment]
Yeah, could use some advice on if / how to use the header here - the only thing we accept is a POST over HTTPS to the /accept end point with Hawk auth

**Comment by jvehent** [comment]
You can ignore it. We have it there as a general recommendation for all services, since we don't know who will be consuming the service in the end, but if you know a recommendation isn't useful at all, it's ok to ignore it.

**Comment by clouserw** [comment]
Ok, closing this.
