### ISSUE TITLE
Add Screenshots client to database

### ISSUE THREAD

**Issue by clouserw** [mozilla/watchdog-proxy#194]
Please add (and give to us) the Screenshots credentials and production URL for the watchdog service.

**Comment by clouserw** [comment]
@oremj any news here?

**Comment by oremj** [comment]
I didn't get a notification for this issue, so this is the first I've heard of it. I can set this up today.

**Comment by oremj** [comment]
The production URL is https://watchdog-proxy.services.mozilla.com/

**Comment by oremj** [comment]
I have the watchdog credentials in our secrets store already, do you want them e-mailed to you as well?

**Comment by clouserw** [comment]
No, we don't need them as long as Screenshots has them and can connect.  When we're ready to configure Screenshots we can just say "look in the secret store" and you'll know what that means? :)  If so, we can close this.

**Comment by oremj** [comment]
I think this is covered by: https://github.com/mozilla-services/cloudops-deployment/issues/2589

**Comment by clouserw** [comment]
Cool.  Thank you!
