### ISSUE TITLE
Add SENTRY_DSN to {dev,stage,prod} deployments

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#198]
Just closed issue #193 to add Sentry reporting to watchdog, merged the code to master. 

This now needs a `SENTRY_DSN` env var to activate on {dev,stage,prod} environments - there's a different value for each, which should be available in the corresponding project settings:

* https://sentry.prod.mozaws.net/operations/watchdog-proxy-dev/settings/keys/
* https://sentry.prod.mozaws.net/operations/watchdog-proxy-stage/settings/keys/
* https://sentry.prod.mozaws.net/operations/watchdog-proxy-prod/settings/keys/

(Only a few of us should have access to those pages)

**Comment by oremj** [comment]
This has been deployed.
