### ISSUE TITLE
Build HMAC Authorization infrastructure

### ISSUE THREAD

**Issue by wresuolc** [mozilla/watchdog-proxy#2]
The security team recommends we use Hawk.  @ameihm0912 will follow up with some documentation of how it is used at Mozilla.

- The `Authorization` header must be included with all requests from consumers.  If it is absent, immediately reply with a `401`.

**Comment by wresuolc** [comment]
walkthrough @ https://blog.mozilla.org/services/2015/02/05/whats-hawk-and-how-to-use-it/

From aaron:
- https://github.com/hueniverse/hawk
- https://github.com/hueniverse/hawk#protocol-example
- FxA auth server makes use of it:
  - https://github.com/mozilla/fxa-auth-server/blob/master/docs/overview.md
  - https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md
- Hawk auth is implemented in one of our services (this one is go)
  - https://github.com/mozilla-services/tigerblood

**Comment by lmorchard** [comment]
Assigning myself as I'm just starting to look into adding this.
