### ISSUE TITLE
Process the message queue

### ISSUE THREAD

**Issue by wresuolc** [mozilla/watchdog-proxy#3]
New messages will appear in the queue and we need to process them.

- Build a worker that wakes up either periodically or on a trigger from the queue
- The worker will take the message from the queue and send it to PhotoDNA
- Maximum 5 requests per second and 10MM submissions a month

### From the PRD:
A worker process is continually paring down the queue by sending items to PhotoDNA in first in, first out order, taking care to respect its rate limit. These requests should conform to the [documentation for PhotoDNA's Match endpoint](https://developer.microsoftmoderator.com/docs/services/57c7426e2703740ec4c9f4c3/operations/57c7426f27037407c8cc69e6). Notes:

The enhance parameter should be set to true.
The Enable-Evaluation header should be set to always.
The timestamp of the submission to PhotoDNA should be recorded.

Upon confirmation from PhotoDNA that an image is positive or negative, Watchdog sends a request to the  URL specified in the consumer's initial request (in step 1):

> POST /watchdog/verify/negative?file_id=012345677890&nonce=abcdefghij HTTP/1.1
> Host: screenshots.firefox.com
> Content-Type: application/json
>  
> {
>     "watchdog_id": "5a416211-f09e-4183-a8e1-4137acfa10f2",
>     "positive": false
> }

**Comment by lmorchard** [comment]
Got a start on this with two functions:

* https://github.com/mozilla/watchdog-proxy/blob/master/functions/pollQueue.js
* https://github.com/mozilla/watchdog-proxy/blob/master/functions/processQueueItem.js

pollQueue is [invoked every minute by CloudWatch](https://github.com/mozilla/watchdog-proxy/blob/master/serverless.yml#L139) and polls the queue for most of a minute. As messages arrive from SQS, they are passed to an async invocation of the processQueueItem function to do the real work. Rate limiting applies to the speed at which processQueueItem is called.

**Comment by lmorchard** [comment]
Assigning myself belatedly, as I've been working on this for awhile today

**Comment by lmorchard** [comment]
Going to say this one is done, but file some followups for additional functionality
