### ISSUE TITLE
Get a data review

### ISSUE THREAD

**Issue by wresuolc** [mozilla/watchdog-proxy#33]
Documentation @ https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md

**Comment by wresuolc** [comment]
@rayborn -- please review the metrics.md for any concerns with data collection

**Comment by chenba** [comment]
Just want to note that the metrics doc has been updated since @wresuolc's previous comment.

**Comment by rayborn** [comment]
@wresuolc - after talking to other stewards since this is a unique product I have the following clarifications.  Since this would involve link existing user accounts to this data, this will be probably considered higher category.  That said, it sounds like we already have legal approval on this.  We'd simply want legal's approval to be in a referable place to make it explicit in the review.  We would also need the [review request](https://github.com/mozilla/data-review/blob/master/request.md) filled in, and put in a public location (raw text here is fine).

**Comment by wresuolc** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

> 1) What questions will you answer with this data?

     Overall throughput performance:
         Consumer submission to submission to PhotoDNA (time in queue)
         Response from PhotoDNA (time waiting for reply)
         Response to consumer API (time to reply)
         The sum of the above to give an easy health measure
     Throughput data for positive identifications since they require manual intervention:
         Number of positively flagged images
             Breakdown of images not yet reviewed and under review
         Number of images confirmed vs falsely identified
     The number of items in the message queue
     Total number of images processed
         Breakdown of positive vs negative responses

> 2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

These are for health of the application as well as evaluating whether it's worth the cost to continue to maintain the application

> 3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

None, they are all essentially health metrics.

> 4) Can current instrumentation answer these questions?

No, this is a new application

> 5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the Mozilla wiki.   
> **Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

Please see https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md

> 6) How long will this data be collected?  Choose one of the following:
> * This is scoped to a time-limited experiment/project until date MM-DD-YYYY.
> * I want this data to be collected for 6 months initially (potentially renewable).
> * I want to permanently monitor this data. (put someone’s name here)

I want this data to be collected for 6 months initially (potentially renewable).

> 7) What populations will you measure?

Anyone using the service.  In this case, people who upload screenshots but in the future it could be other services at Mozilla.

> 8) If this data collection is default on, what is the opt-out mechanism for users?

Opt-out would be don't upload images to the screenshots servers.  There are alternatives to save to disk or copy to clipboard.

> 9) Please provide a general description of how you will analyze this data.

Redash graphs

> 10) Where do you intend to share the results of your analysis?

Within the team/mozilla.

**Comment by wresuolc** [comment]
This is waiting on a=legal

**Comment by rayborn** [comment]
r+ due to internal escalation / approval through legal. Given the unique nature of this looks like their approval is all that's required after confirming with rjweiss.

**Comment by clouserw** [comment]
Thank you!
