### ISSUE TITLE
Implement some more run-time configuration?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#36]
The stack has a "Config" table in DynamoDB. So far, it just uses that to maintain a hacky mutex to ensure only one queue poller function is running at any given time.

This table can be manually edited from the AWS console - or even via scripted tooling. So, it might be handy for some further run-time configuration to give ops some tuning parameters & options without needing to redeploy. 

Some ideas:

* `pause` - a flag to pause queue processing - e.g. the poller immediately exits on scheduled invocation
* `rateLimit` / `rateLimitPeriod` - override the hardcoded 5/second rate limit in queue poller
* `credentials` - run-time configuration of upstream service credentials & URL?

Any other things worth tweaking at runtime?

**Comment by chenba** [comment]
+1 on a rate limit config.  And perhaps 0 on teh rate limit can effectively be the `pause` flag.
