### ISSUE TITLE
Add monitoring URLs

### ISSUE THREAD

**Issue by wresuolc** [mozilla/watchdog-proxy#4]
Please add URLs:

`/__heartbeat__`
`/__version__`

@oremj -- do we need a `/__lbheartbeat__`  ?

**Comment by lmorchard** [comment]
> If this ends up running on EC2, behind and ELB, then it would be great to have a /__lbheartbeat__ endpoint.

Unless we've got red flags to change direction, so far I think we're aiming at a stack using Lambda + SNS + SQS and maybe DynamoDB.

**Comment by wresuolc** [comment]
Yep, that's what we talked about.  We haven't done that kind of app before, we're doing it based on that meeting.  @oremj can you confirm that's what you're wanting?  Since you're doing the deployment work I think this is up to you.  Thanks

**Comment by oremj** [comment]
Sorry, the -proxy part threw me off, I thought maybe this was a separate service. I might also be confused on the architecture. Is this service a queue processor, HTTP listener or both?

If it's just a queue processor, then we won't need any endpoints, we will just monitor the Lambda and SQS metrics.

If the service does have an HTTP listening component, then we should have `/__heartbeat__` and `/__version__`. No need for `/__lbheartbeat__` if it's lambda/api gateway.

**Comment by lmorchard** [comment]
It's a service that accepts HTTP requests to queue jobs. The jobs get processed as requests to an upstream web service with rate limiting applied. As each job is completed, HTTP requests are made back to the original client site with the results.
