### ISSUE TITLE
Record PhotoDNA metadata

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#43]
From the PRD:
> Step 4c: Record PhotoDNA metadata
> Upon confirmation from PhotoDNA that an image is positive or negative, Watchdog records important information of the response from PhotoDNA for future inspection.

Property | Description | Example
-- | -- | --
photodna_tracking_id | Identifier of the request to PhotoDNA | 1_photodna_a0e3d02b-1a0a-4b38-827f-764acd288c25
is_match | Whether the image is known to be abusive to PhotoDNA | false

Additionally, the receipt timestamp should be logged.

**Comment by lmorchard** [comment]
Follow up questions:
- Who's going to access this?
- Where should it be recorded? (assuming somewhere useful to whomever needs to access it)
- Is the `photodna_tracking_id` sufficient for identifying the image? (i.e. is there an upstream PhotoDNA dashboard on which we can search by that ID?)

**Comment by lmorchard** [comment]
Also, considering #44, I think a few more properties should be recorded:
* Job timestamp
* Name of consumer application
* Watchdog ID of job
* PhotoDNA tracking ID
* Notes field from job

**Comment by wresuolc** [comment]
> Who's going to access this?
> Where should it be recorded? S3? DynamoDB? other? (assuming somewhere useful to whomever needs to access it)
> Is the photodna_tracking_id sufficient for identifying the image? (i.e. is there an upstream PhotoDNA dashboard on which we can search by that ID?)

There are no upstream dashboards.  For now, let's either no-op until I know more, or just set up to dump into an s3 bucket (what I'm lobbying for).

**Comment by wresuolc** [comment]
> Also, considering #44, I think a few more properties should be recorded:
> 
>     Job timestamp
>     Name of consumer application
>     Watchdog ID of job
>     PhotoDNA tracking ID
>     Notes field from job

This seems appropriate.  I think we should dump everything we know about the item in a text file in s3.
