### ISSUE TITLE
Verify ping centre metrics are working as expected

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#96]
On the dev stack, metric pings are going to a mock endpoint within the dev stack itself rather than Ping Centre. We can inspect what the stack is doing in dev stack CloudWatch logs.

But, once we have a staging stack, we should send pings to Ping Centre staging and verify they're doing what we expect.

**Comment by clouserw** [comment]
@ncloudioj Les finished #187 so I think we can verify the last ping now -- the heartbeat one.  There is an example of what you should be seeing at https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md#periodic-queue-metrics

**Comment by ncloudioj** [comment]
@lmorchard @clouserw Yes, PC received approx. 9000 heartbeat pings on 2018-09-06, but the ETL job detected a minor issue in the payload, which prevented it from loading the metrics to the database. The `items_in_queue`, `items_in_progress`, and `items_in_waiting` were all of the string type in the payload, I believe the integer should be the expected type here. Could you take a look at this?

Having another question about the heartbeat ping, are we planning on using this ping for the system health monitoring? Or for some other purposes? Noticed that most of the heartbeat pings had 0 `items-*` values, and being reported once per second from each poller. Just wanting to ensure we were not accidentally sending excessive metrics. If that was the expected cadence, please just disregard this question.

**Comment by lmorchard** [comment]
> The items_in_queue, items_in_progress, and items_in_waiting were all of the string type in the payload, I believe the integer should be the expected type here. Could you take a look at this?

Looks like I'm just passing along the result of the Amazon SQS API call, which has all string values for these counts. [Opened a PR to wrap them in parseInt](https://github.com/mozilla/watchdog-proxy/pull/188).

> Having another question about the heartbeat ping, are we planning on using this ping for the system health monitoring?

Health monitoring, along with the other two ping types.

> Noticed that most of the heartbeat pings had 0 items-* values, and being reported once per second from each poller. Just wanting to ensure we were not accidentally sending excessive metrics. If that was the expected cadence, please just disregard this question.

[This was part of my concern in Issue 177](https://github.com/mozilla/watchdog-proxy/pull/177#issuecomment-417749373): Since most queue jobs get processed in less than a second - at least at our current testing load - it's likely that this heartbeat ping will usually have all zeroes. And it's not really practical to run the heartbeat more than once per second, given that the API it's calling can be relatively slow to respond.

If that's an excessive ping rate, and most of the counts will be zero, should we maybe skip sending a ping if everything is zero? Not sure how that would help / hinder analysis later.

**Comment by lmorchard** [comment]
> being reported once per second from each poller

Also, FWIW, there should only be *one* metric poller at any given time. The function should start up every minute and run for just short of a minute, sending a ping every second or so (plus/minus processing time). Each run of the poller should have a unique ID, and there shouldn't be parallel instances running.

**Comment by clouserw** [comment]
Thank you!  I filed #190 to get this updated to production
