### ISSUE TITLE
Validate that this thing works

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#98]
We have unit tests. We should have load testing and end-to-end integration testing of the service.

**Comment by clouserw** [comment]
mbrandt is running point on this.  We're blocked on getting stage up and running.  Jeremy says today or tomorrow

**Comment by chenba** [comment]
It works! :D

**Comment by clouserw** [comment]
This is for @m8ttyb

**Comment by clouserw** [comment]
I'm going to close this since @m8ttyb will open new issues for anything he finds
